### ISSUE TITLE
Windows binary release

### ISSUE THREAD

**Issue by SebastienTs** [osamu620/OpenHTJ2K#126] opened 2022-07-18 15:14 UTC
Hello,

I have tried to compile the project with Cmake + Visual Studio 2017 (Windows 10) but I get errors related to undefined symbols (the errors are different without ENABE_AVX2 but it still does not compile).

Do you plan some binary releases soon (probably the easiest for me as I only need the command line executable for testing)?

Best,
S.

**Comment by osamu620** [comment] 2022-07-19 04:21
@SebastienTs 
Hi, I'll try to reproduce the error with Visual Studio 2017. I'll get back to you soon.

**Comment by osamu620** [comment] 2022-07-21 13:54
@SebastienTs 
The issue has been fixed by #129. Now Visual Studio 2017 should be able to compile the project. The coding/decoding speed with VS2017 would be slightly slower than those with VS2019 or VS2022.

Currently, there is no plan to release any binaries. (Because I'm not familiar with the distribution of binaries that can be used universally)

**Closed by osamu620** 2022-07-21 13:54 UTC

**Comment by SebastienTs** [comment] 2022-07-21 17:11
Thanks, it now compiles correctly!
